Assignment4AyseParlar/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^school/', include('school.urls')),
    url(r'^$', 'school.views.home'),
]

school/urls.py
from django.conf.urls import url
from school import views

urlpatterns = [
    url(r'^students/$', views.StudentListView.as_view()),
    url(r'^teachers/$', views.TeacherListView.as_view()),
    url(r'^courses/$', views.CourseListView.as_view()),
    url(r'^add_student/$', views.StudentCreateView.as_view()),
    url(r'^add_teacher/$', views.TeacherCreateView.as_view()),
    url(r'^add_course/$', views.CourseCreateView.as_view()),
    url(r'^add_registration/$', views.RegistrationCreateView.as_view()),
]

school/models.py
from django.db import models

# Create your models here.


class Student(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    courses = models.ManyToManyField('Course', related_name='students', blank=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class Course(models.Model):
    teacher = models.ForeignKey('Teacher')
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=10)
    classroom = models.CharField(max_length=10)
    times = models.TextField()

    def __str__(self):
        if self.students.count():
            return self.name + ' // STUDENTS=[' + (', '.join(map(str, self.students.all()))) + ']'
        else:
            return self.name


class Teacher(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    office_details = models.TextField()
    phone = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.first_name + ' ' + self.last_name

school/forms.py
from django import forms

from school.models import *


class RegistrationForm(forms.Form):
    course = forms.ModelChoiceField(queryset=Course.objects.all())
    student = forms.ModelChoiceField(queryset=Student.objects.all())

    def save(self, commit=True):
        self.cleaned_data['student'].courses.add(self.cleaned_data['course'])

school/views.py
from django.shortcuts import render_to_response


# Create your views here.
from django.views.generic import CreateView, ListView, FormView

from school.forms import RegistrationForm
from school.models import *


def home(request):
    return render_to_response('home.html')


class StudentCreateView(CreateView):
    success_url = '/school/students/'
    template_name = 'form_template.html'
    model = Student
    fields = ['first_name', 'last_name', 'email']


class TeacherCreateView(CreateView):
    success_url = '/school/teachers/'
    template_name = 'form_template.html'
    model = Teacher
    fields = ['first_name', 'last_name', 'office_details', 'phone', 'email']


class CourseCreateView(CreateView):
    success_url = '/school/courses/'
    template_name = 'form_template.html'
    model = Course
    fields = ['teacher', 'name', 'code', 'classroom', 'times']


class RegistrationCreateView(FormView):
    success_url = '/school/courses/'
    template_name = 'form_template.html'
    form_class = RegistrationForm

    def form_valid(self, form):
        form.save()
        return super(RegistrationCreateView, self).form_valid(form)


class StudentListView(ListView):
    template_name = 'list_template.html'
    model = Student


class TeacherListView(ListView):
    template_name = 'list_template.html'
    model = Teacher


class CourseListView(ListView):
    template_name = 'list_template.html'
    model = Course

templates/form_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
    <style type="text/css">
        input, textarea, select, button {
            border-radius: 10px;
        }
    </style>
</head>
<body>
<h1>Create</h1>
<form action="." method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
    <ul>
        <li><a href="/school/students/">Students</a></li>
        <li><a href="/school/teachers/">Teachers</a></li>
        <li><a href="/school/courses/">Courses</a></li>
        <li><a href="/school/add_student/">Add Student</a></li>
        <li><a href="/school/add_teacher/">Add Teacher</a></li>
        <li><a href="/school/add_course/">Add Course</a></li>
        <li><a href="/school/add_registration/">Add Registration</a></li>
    </ul>
</body>
</html>

templates/list_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List</title>
</head>
<body>
<h1>List</h1>
<table>
    <thead>
    <tr>
        {% if student_list %}
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Courses</th>
        {% elif course_list %}
            <th>Teacher</th>
            <th>Name</th>
            <th>Code</th>
            <th>Classroom</th>
            <th>Times</th>
            <th>Students</th>
        {% elif teacher_list %}
            <th>First Name</th>
            <th>Last Name</th>
            <th>Office Details</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Courses</th>
        {% endif %}
    </tr>
    </thead>
    <tbody>
    {% if student_list %}
        {% for student in student_list %}
        <tr>
            <td>{{ student.first_name }}</td>
            <td>{{ student.last_name }}</td>
            <td>{{ student.email }}</td>
            <td>{% for course in student.courses.all %}{{ course.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
        </tr>
        {% endfor %}
    {% elif course_list %}
        {% for course in course_list %}
        <tr>
            <td>{{ course.teacher }}</td>
            <td>{{ course.name }}</td>
            <td>{{ course.code }}</td>
            <td>{{ course.classroom }}</td>
            <td>{{ course.times }}</td>
            <td>{% for student in course.students.all %}{{ student }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
        </tr>
        {% endfor %}
    {% elif teacher_list %}
        {% for teacher in teacher_list %}
        <tr>
            <td>{{ teacher.first_name }}</td>
            <td>{{ teacher.last_name }}</td>
            <td>{{ teacher.office_details }}</td>
            <td>{{ teacher.phone }}</td>
            <td>{{ teacher.email }}</td>
            <td>{% for course in teacher.course_set.all %}{{ course.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
        </tr>
        {% endfor %}
    {% endif %}
    </tbody>
</table>
</body>
</html>